sudo: required
language: node_js
node_js:
- node
env:
  matrix:
  - SERVER_IP_ADDRESS=104.210.106.138
  global:
    secure: Kn8amqLpb7I60kPG+hnZws7wSkDqGLDdDiIzRNpn1WgtTf4f+NzHp46Bkd/sJS9n/iQOoBE2O6E97Q4nXsSrCH+8UMjdzikDnglVBpfCGfNb1kHqAJvGDfnObCGXPKNz7HoFEkB6MFWyZfG672m2ekiAMr5HPGYn1QDvS7fGXoHtBJZ16YvNqsslO9ZUhr5JW7OzA5O0yw/x/65j1RjH0jR/6cP2sSRHxtbZWbsasvZYQC+2zapMNJRuhA07AwmxtLBnDbhEQ3yGW83tBkoK0j2nj0UAMYrN+Inpod52hxWIE6wYQ5nMMn28AXXUUPAQ+7lyHz6WY4BU+Qc/5sjaGIStkV6UagndudLWIBW0HgN+2Bm8zvMkC2KCuQHjJ+0XoaE/8udPbgUVpDxUeOlI2FQeuH5n/4nwuVgCYDp7kvnIehuVB56O6Qmmlr9x/7KAzOWTClw+iVqOGmm66ZqDjLENzFBnNthkcMdMzUJ3rLnH2oQ9Z4p2Ufy2Qhl2aHj42LzC2rERtlNlxymyPqWJo9ujBemi++cd/QcGLipjo1ufndWZcWtBOd5vwi3j7x9s3lx9Nc3/6tRHw0uM0rIvyLDiqjccz+oo80HuAaNiVGZajz51XBEADi22Mt1qDz1NzTxI23KsTWHmEZScbRcnfIOb7IDHP97YfNQjmUtGkeQ=
services:
- docker
addons:
  ssh_known_hosts: 104.210.106.138
before_install:
- echo "ledgerappuser/ledgeriumgovernance_server"
- docker pull ledgerappuser/ledgeriumgovernance_server || true
- echo "Testing Docker Hub credentials"
- BUILDID="build-$RANDOM"
- echo $BUILDID
- docker build --pull --cache-from ledgerappuser/ledgeriumgovernance_server --tag
  ledgerappuser/ledgeriumgovernance_server:v$BUILDID .
- docker login -u=$DOCUSENAME -p=$DOCPASSWRD
- echo "Docker Hub credentials are working"
- docker tag ledgerappuser/ledgeriumgovernance_server ledgerappuser/ledgeriumgovernance_server:latest
- docker tag ledgerappuser/ledgeriumgovernance_server ledgerappuser/ledgeriumgovernance_server:v$BUILDID
script:
- docker ps -a
after_success:
- docker push ledgerappuser/ledgeriumgovernance_server:v$BUILDID && docker push ledgerappuser/ledgeriumgovernance_server:latest
before_deploy:
- openssl aes-256-cbc -K $encrypted_887211266452_key -iv $encrypted_887211266452_iv
  -in deploy_rsa.enc -out ./deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_rsa
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_rsa
- rsync -r --delete-after --quiet ./deploy_script.sh ledgerappuser@104.210.106.138:~/ledgerium/ledgeriumtools/output
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i ./deploy_rsa ledgerappuser@104.210.106.138 "cd ~/ledgerium/ledgeriumtools/output
    && bash ./deploy_script.sh $BUILDID $DOCUSENAME"
  on:
    branch: master
dd:
  secure: Vo7FDhFGGN5q9pJewRTk/DFYbFDpRmvBsFIHL7zRKSgHeJa/jim3Ou3PcCZ9xoAuC3GVTTiEMLzFnmJBdk7JrMvqtn4WTmV9dzZp7O6SKVPJuvuBgqIxdtTCStDVjxXj6U5KKubQXh1StvxtN10m55nPUUBTrUl/crXlooa13F4ASrNhgzzCbVUogUOY83cJ4uBJfs0lZ66ZxGatKPyqX3cq7n4q3pTdxqSqpoP5v8zlzht2cDoBiSuAJ2XmyLapmmqcxaNWNByG1eaDdQBKFuLiZ3nnU0sucWhlY+40A+dnydIcHFBeM9puf+FCzACf/JWc+w+iqe2yLadIrC9OBIwrfKlbrLCh7D/mYo4ma6Wr05DcBWa355uetX24n/t9R2fP/CGXM8ChRZccAM4filZgdI+2rd5LyXl7RC937h+Xx4a4r8wbl8cehKLnm0S3e3ydcNUWHRwo15mN9SgGbX3Wrvr698ZfRs6LXG/TXD3nHO9BBWkVHEs6DJsmsYFWKpEQcpmXqS6o4A09GS/B9q6NYtvnCH0ebNpGyBQ//7pwDaVba0JoaFrBniHv3URez3KMHzklgDPz5ZXtWgYxD1cxUYjLNY7vBj8weZPwo4hxjLjOwmekkQW54dpDKnhAVlm2lnNOP5pHE5fbbYUHiR/Lo6CdImPP8qnCB4OEVUc=
