[parity]
chain = "config/spec.json"
base_path = "/opt/parity"
[network]
port = 30300
reserved_peers = "bootnodes.txt"
nat = "extip:13.77.149.177"
[ipc]
disable = false
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts", "secretstore", "pubsub"]
[rpc]
port = 8540
apis = ["web3", "eth", "net", "parity", "traces", "rpc"]
interface = "all"
cors = ["all"]
[ui]
port = 8180
[websockets]
port = 8546
[account]
password = ["node.pwd"]
[mining]
engine_signer = "0x005c88b694531caf1e6eda4de17d93c3725de3c0"
reseal_on_txs = "none"
force_sealing = true
